# Day 4: Lesson: 3D Rotations

CSSE 461 / Rose-Hulman Institute of Technology / Winter 2025-26

Kyle Wilson

This notebook is a sandbox for exploring 3D rotations.

In [2]:
# this is the best 3D rotations import in Python
import numpy as np
from scipy.spatial.transform import Rotation as R


In [3]:
# Let's look at a random 3D rotation:
rot = R.random().as_matrix()

# rot @ rot.T 
rot

array([[ 0.94662836,  0.09543565,  0.30787461],
       [ 0.18088188, -0.9478716 , -0.26233791],
       [ 0.26678921,  0.30402545, -0.91454472]])

scipy has its own internal representation of 3D rotations called `scipy.spatial.transform._rotation.Rotation`. (Under the hood, it uses a slick representation called a unit quarternion. The math is very slick, but not for today.)

For our uses, we can display the same rotation in different ways:

1. as a rotation matrix: `.as_matrix()`
1. as a unit quaternion: `.as_quat()`
1. as a rotation vector: `as_rotvec()`

The first and third options are worth our attention today.

In [ ]:
# camera - to - world : NO
# world - to - camera : YES
z = np.array([0, 0, 1])
rot @ z


array([ 0.30787461, -0.26233791, -0.91454472])

In [6]:
# this is camera - to - world
rot.T

array([[ 0.94662836,  0.18088188,  0.26678921],
       [ 0.09543565, -0.9478716 ,  0.30402545],
       [ 0.30787461, -0.26233791, -0.91454472]])

In [7]:
rot @ rot.T

array([[ 1.00000000e+00,  1.38777878e-17,  5.55111512e-17],
       [ 1.38777878e-17,  1.00000000e+00, -5.55111512e-17],
       [ 5.55111512e-17, -5.55111512e-17,  1.00000000e+00]])